### PR TITLE
Add python 2.7 support

### PR DESCRIPTION
**Pull request by RJMW**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
So, it‘s the same state as before. AppVeyor is failing.

@bgruening, just to get you in the conversation, @RJMW contacted me and asked if we could try to get the Python 2.7 version working (especially on macOS)

**Comment by bgruening** [comment]
@m-rossi we can skip windows builds for the moment? I'm a little bit puzzled with this one, as I would expect the Windows builds to be the unproblematic one :)

**Comment by m-rossi** [comment]
@RJMW proposed that, too.

**Comment by bgruening** [comment]
Uha it is green! Thanks @RJMW! Do you have a windows ;)

**Review by bgruening — APPROVED** [review]

**Comment by m-rossi** [comment]
Perfect, thanks @RJMW

**Pull request merged**
